### ISSUE TITLE
Add events to example app

### ISSUE THREAD

**Issue by timsayshey** [gahabeen/vue-formulate-extended#4]
The current example app focuses on iMask examples but would be better to see the `on events` features in action.

**Comment by gahabeen** [comment]
@timsayshey Check out the new stable version! And careful there has been breaking changes when registering the plugin at least.
https://codesandbox.io/s/events-propagation-b2vsf?file=/src/components/Sandbox.vue
https://github.com/gahabeen/vue-formulate-extended
