### ISSUE TITLE
Safe to use with Composition API?

### ISSUE THREAD

**Issue by jpeterman** [gahabeen/vue-formulate-extended#5]
@gahabeen Hey there, I noticed that there is a dependency on the composition api plugin.  I was wondering if this is safe to use in production?  I'm new to the composition api plugin, but the documentation makes it sound like it's been released more for feedback vs production use.  Any thoughts on that?

Reference: 
https://composition-api.vuejs.org/#more-flexibility-requires-more-discipline
` It may also receive braking changes as this proposal is updated, so we do not recommend using it in production at this stage.`

Definitely would like to use the schema event features you've made available if possible. I'm using it for a client though, so I want to make sure it's safe.

Thanks!
Jason

**Comment by gahabeen** [comment]
Hey @jpeterman, really valid remark. I removed the dependency. Not available from version `1.0.3` without `@vue/composition-api` plugin ;)
